stages:
  - deploy_test
  - deploy_prod

before_script:
  - cd /opt/dokploy
  - git pull origin $CI_COMMIT_REF_NAME

# Step 1: Deploy to a test server (on 'develop')
deploy_to_test:
  stage: deploy_test
  script:
    - sudo systemctl restart dokploy
  only:
    - develop
    # - main
  tags:
    - vps-test

# Step 2: Deployment to a production server (only 'main')
deploy_to_prod:
  stage: deploy_prod
  script:
    - sudo systemctl restart dokploy
  only:
    - main
  tags:
    - vps-prod
